export { default as PrimaryButton } from "./components/buttons/Primary";
export { default as SecondaryButton } from "./components/buttons/Secondary";
export { default as Sidebar } from "./components/sidebar/Sidebar";
export { default as Loader } from "./components/sidebar/Sidebar";
export { default as ProtectedRoute } from "./components/routes/ProtectedRoute";
export { AuthProvider, AuthContext } from "./hooks/sign-in/useAuth";
export { usePermission } from "./hooks/permissions/usePermissions";
export { Loading } from "./components/loader/Loading";
//PAGES
export { default as Dashboard } from "./pages/Dashboard";
export { default as Home } from "./pages/Home";
export { default as Customers } from "./pages/Customers";
export { default as PrimeUser } from "./pages/PrimeUsers";
export { default as Expected } from "./pages/Expected";
export { default as TestUsers } from "./pages/TestUsers";
export { default as Balance } from "./pages/Balance";
export { default as Reports } from "./pages/Reports";
export { default as OnlinePayment } from "./pages/OnlinePayment";
export { default as Bonus } from "./pages/Bonus/Bonus";
export { default as Roles } from "./pages/Roles";
export { default as Members } from "./pages/Members";
export { default as Orders } from "./pages/Orders";
export { default as OrdersCheck } from "./pages/Orders/Check";
export { default as ActionsHistory } from "./pages/ActionsHistory";
export { default as Banners } from "./pages/Banners";
export { default as OrdersFailed } from "./pages/OrdersFailed";
export { default as Slides } from "./pages/Slides";
export { default as Blogs } from "./pages/Blog";
export { default as ReceiveOrders } from "./pages/ReceiveOrders";
export { default as Shops } from "./pages/Shops";
export { default as AppVersions } from "./pages/AppVersions";
export { default as SignIn } from "./pages/sign-in/intex";
export { default as CustomerSingle } from "./pages/CustomerSingle";
